### ISSUE TITLE
unit test failed on angular-mocks

### ISSUE THREAD

**Issue by liujoey** [vesparny/angular-kickstart#20]
I'm pretty new to the angular world. (Having few years web develop experience though)

When I clone and try to run unit tests on this project, I got one error.
It seems that Chrome browser doesn't understand `require`, here is the error message:

```
Chrome 39.0.2171 (Linux) ERROR
  Uncaught ReferenceError: require is not defined
  at /home/joey/workspace/eva/client/src/vendor/angular-mocks/index.js:9
ERROR [karma]: [TypeError: Cannot set property 'results' of undefined]
```

By searching the google, I learnt that `browserify` can do the trick, but I just don't know how to integrate with this kickstart project. Please help, thank you very much.

**Comment by vesparny** [comment]
What version of angular-kickstart are you using?
Could you provide some detail more?

**Comment by liujoey** [comment]
I had just cloned the github repo, so I guess it's the latest version.
I'm running Ubuntu Linux 14.10, Google Chrome installed. After I clone the repo and run npm install & bower install etc. I can start the server with `gulp serve`, and `gulp test:e2e` also passed without a problem. 

But when I run `gulp test:unit` or `gulp serve:tdd`, I got the same error for both Chrome and PhantomJS.

```
[15:26:11] Starting 'tdd'...
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/__test/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Linux)]: Connected on socket JV2rLQQ9zCpAhCkARlby with id 17167764
PhantomJS 1.9.8 (Linux) ERROR
  ReferenceError: Can't find variable: require
  at /home/joey/workspace/eva/client/src/vendor/angular-mocks/index.js:9
ERROR [karma]: [TypeError: Cannot set property 'results' of undefined]
TypeError: Cannot set property 'results' of undefined
  at [object Object].onBrowserComplete (/home/joey/workspace/eva/node_modules/karma-html-reporter/index.js:43:25)
  at [object Object].<anonymous> (/home/joey/workspace/eva/node_modules/karma/lib/events.js:15:22)
  at [object Object].EventEmitter.emit (events.js:117:20)
  at [object Object].onComplete (/home/joey/workspace/eva/node_modules/karma/lib/browser.js:145:13)
  at Socket.<anonymous> (/home/joey/workspace/eva/node_modules/karma/lib/events.js:15:22)
  at Socket.EventEmitter.emit [as $emit] (events.js:117:20)
  at SocketNamespace.handlePacket (/home/joey/workspace/eva/node_modules/karma/node_modules/socket.io/lib/namespace.js:335:22)
  at Manager.onClientMessage (/home/joey/workspace/eva/node_modules/karma/node_modules/socket.io/lib/manager.js:488:38)
  at WebSocket.Transport.onMessage (/home/joey/workspace/eva/node_modules/karma/node_modules/socket.io/lib/transport.js:387:20)
  at Parser.<anonymous> (/home/joey/workspace/eva/node_modules/karma/node_modules/socket.io/lib/transports/websocket/default.js:36:10)
  at Parser.EventEmitter.emit (events.js:95:17)
  at Parser.parse (/home/joey/workspace/eva/node_modules/karma/node_modules/socket.io/lib/transports/websocket/default.js:343:12)
  at Parser.parse (/home/joey/workspace/eva/node_modules/karma/node_modules/socket.io/lib/transports/websocket/default.js:346:19)
  at Parser.add (/home/joey/workspace/eva/node_modules/karma/node_modules/socket.io/lib/transports/websocket/default.js:315:8)
  at Socket.<anonymous> (/home/joey/workspace/eva/node_modules/karma/node_modules/socket.io/lib/transports/websocket/default.js:169:17)
  at Socket.EventEmitter.emit (events.js:117:20)
  at Socket.<anonymous> (_stream_readable.js:746:14)
  at Socket.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:408:10)
  at emitReadable (_stream_readable.js:404:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:526:21)

[15:26:15] 'tdd' errored after 3.23 s
[15:26:15] Error: 1
  at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
  at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
  at Gulp.EventEmitter.emit (events.js:95:17)
  at Gulp.Orchestrator._emitTaskDone (/home/joey/workspace/eva/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
  at /home/joey/workspace/eva/node_modules/gulp/node_modules/orchestrator/index.js:275:23
  at finish (/home/joey/workspace/eva/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at cb (/home/joey/workspace/eva/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
  at removeAllListeners (/home/joey/workspace/eva/node_modules/karma/lib/server.js:220:7)
  at Server.<anonymous> (/home/joey/workspace/eva/node_modules/karma/lib/server.js:231:9)
  at Server.g (events.js:180:16)
  at Server.EventEmitter.emit (events.js:117:20)
  at net.js:1273:10
  at process._tickCallback (node.js:415:13)

WARN [PhantomJS 1.9.8 (Linux)]: Disconnected (1 times), because no message in 10000 ms.

/home/joey/workspace/eva/node_modules/karma-html-reporter/index.js:43
                browserResult.results = browser.lastResult;
                                      ^
TypeError: Cannot set property 'results' of undefined
  at [object Object].onBrowserComplete (/home/joey/workspace/eva/node_modules/karma-html-reporter/index.js:43:25)
  at [object Object].<anonymous> (/home/joey/workspace/eva/node_modules/karma/lib/events.js:15:22)
  at [object Object].EventEmitter.emit (events.js:117:20)
  at [object Object]._onTimeout (/home/joey/workspace/eva/node_modules/karma/lib/browser.js:53:15)
  at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

**Comment by vesparny** [comment]
the issue is about **karma-html-reporter**.
Could you try to remove it from the karma conf?

**Comment by liujoey** [comment]
no, it's not. I removed the html-reporter, the error is still there.

I think the problem is really about the `require` function, this function should only work in node.js app, but when we do the test, karma launch the Chrome browser and tries to load some js files, but the browser just doesn't know what is `require`.

After I delete angular-mocks and run the unit test again, now the error becomes `angular/index.js` :

```
Chrome 39.0.2171 (Linux) ERROR
  Uncaught ReferenceError: require is not defined
  at /home/joey/workspace/eva/client/src/vendor/angular/index.js:9
```

So, yes, I think it's about the browser doesn't understand what is `require`, but I don't know how to solve it.

**Comment by vesparny** [comment]
try to update the master.
it should be fixed, I just realease a new version.

**Comment by liujoey** [comment]
yes, it works now, thank you.
