### ISSUE TITLE
Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by liujason** [vesparny/angular-kickstart#24]
I just got the error below after following the Getting started doc on a freshly cloned repo.

```
$ gulp serve
util.js:634
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:634:43)
    at Object.<anonymous> (c:\Users\jaliu\Repository\github\angular-kickstart\node_modules\browser-sync\node_modules\http-proxy\lib\http-proxy\index.js:106:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\Users\jaliu\Repository\github\angular-kickstart\node_modules\browser-sync\node_modules\http-proxy\lib\http-proxy.js:4:17)
    at Module._compile (module.js:460:26)
```

**Comment by vesparny** [comment]
It seems to be a problem related to a lib used by browser-sync on windows.
Could you try to upgrade browser-sync to the latest version?
I cannot reproduce on OSX.

**Comment by ognjenkuljic** [comment]
Same error is present on linux, even after update.

**Comment by vesparny** [comment]
The problem is about browser-sync version.
try to replace it in package.json then run npm install

**"browser-sync": "~2.7.1"**

It will work.

I'll update every dependency in the next days and bump a new versione

**Comment by whisher** [comment]
Hi, may be try to delete node_modules before run npm install
I'm having the same issue with *browser-sync* in an other app.
Bye

**Comment by vesparny** [comment]
Version 1.1.0 has been released.
It should work properly now.

Let me know
